### ISSUE TITLE
remove global environment from storage backend

### ISSUE THREAD

**Issue by clux** [lalbuild/lal#7]
## Origin
We currently have a  "global" environment, which is currently used *primarily* as a marker for "all builds succeeded at this version". I.e we'd have a component existing in the global bucket:

`https://artifactory.host/team/component/version/component.tar.gz`

if and only if we have one in **all** our supported environment buckets:
```
https://artifactory.host/team/env/xenial/component/version/component.tar.gz
https://artifactory.host/team/env/centos/component/version/component.tar.gz
```

## Benefits

- `lal update` can figure out what the next allowable version of a component is by simply looking in the global bucket
- `lal export` can work without an explicit environment flag
- `lal query` can work without an explicit environment flag (to see all valid numbers for a component)

## Problems

- `lal publish` must lock-step publish to that bucket last if and only if the two child builds succeeded.
- `lal export component=X` gives you `component` at version X which will be at the current default environment (whatever that was at the time) - which is not particularly useful anyway
- caches of globals must be taken for `lal export`, so:
- environments to be passed around as optional everywhere
- multiple storage of pre-builts is akward enough for artifactory - let's not duplicate it for all `Backend`s

## Proposed solution
Kill global environments, and introduce a changing `supported_environments` in the manifest.

How does this affect backend related subcommands?

### fetch
Not at all. This always needed an environment from the manifest, and it will always just blindly fetch the number that is there. It's up to something else to ensure that these numbers are valid across the `supported_environments`.

### export
This **slightly breaks** export for `lal export component=${version}` scripts that doesn't explicitly specify the environment. These need to upgrade to `lal -e ${env} export component=${version}` when people upgrade lal.

This is a good change; if you are exporting a component you should know what environment it is meant for if you are using it anyway.

## query
Disallow non-explicit environments. I.e. force `lal -e xenial query component` outside a manifested dir (which could **slightly break** small scripts). This is fine, you are not using query to figure out what number goes in the manifest. That's the job of `lal update`.

To compensate for the lack of a view over the join, we could implement a `--zip` flag that queries all environments and intersects. Or we could reclaim what `lal query` means without an environment for that?

## publish
This just makes it easier for `publish`. We're doing less by making the environment mandatory and only allowing the specific buckets as allowed storage locations.

## update
This is where we have to compensate.

Update needs to iterate over all the `supported_environments` and:

- return the largest version in the intersection of all the environments
- ensure that this version is larger than the one currently in the manifest

The last check must be there in case we turned an environment on and off at some point in time.

This iteration is certainly cheaper than uploading to multiple buckets, but it will make `update` ever so slightly slower.

### build
Building in non-default environment warning can now be discarded if you are building in a `supported_environment` (because this override is expected).

### fetch
If people are editing manifest versions directly, then they may find that their branch fails at CI merge level because they specified a version that only existed in one bucket.

**Comment by clux** [comment]
Original diff before we realised this needed a proper writedown:

```diff
diff --git a/src/export.rs b/src/export.rs
index 2c24d6ff..5762ab6c 100644
--- a/src/export.rs
+++ b/src/export.rs
@@ -9,14 +9,14 @@ pub fn export<T: CachedBackend + ?Sized>(
     backend: &T,
     comp: &str,
     output: Option<&str>,
-    env: Option<&str>,
+    env: &str,
 ) -> LalResult<()> {
     if comp.to_lowercase() != comp {
         return Err(CliError::InvalidComponentName(comp.into()));
     }
 
     let dir = output.unwrap_or(".");
-    info!("Export {} {} to {}", env.unwrap_or("global"), comp, dir);
+    info!("Export {} {} to {}", env, comp, dir);
 
     let mut component_name = comp; // this is only correct if no =version suffix
     let tarname = if comp.contains('=') {
diff --git a/src/storage/download.rs b/src/storage/download.rs
index f798b05f..257feaa0 100644
--- a/src/storage/download.rs
+++ b/src/storage/download.rs
@@ -8,7 +8,7 @@ fn is_cached<T: Backend + ?Sized>(
     backend: &T,
     name: &str,
     version: u32,
-    env: Option<&str>,
+    env: &str,
 ) -> bool {
     get_cache_dir(backend, name, version, env).is_dir()
 }
@@ -17,14 +17,13 @@ fn get_cache_dir<T: Backend + ?Sized>(
     backend: &T,
     name: &str,
     version: u32,
-    env: Option<&str>,
+    env: &str,
 ) -> PathBuf {
     let cache = backend.get_cache_dir();
-    let pth = Path::new(&cache);
-    match env {
-        None => pth.join("globals"),
-        Some(e) => pth.join("environments").join(e),
-    }.join(name)
+    Path::new(&cache)
+        .join("environments")
+        .join(env)
+        .join(name)
         .join(version.to_string())
 }
 
@@ -32,7 +31,7 @@ fn store_tarball<T: Backend + ?Sized>(
     backend: &T,
     name: &str,
     version: u32,
-    env: Option<&str>,
+    env: &str,
 ) -> Result<(), CliError> {
     // 1. mkdir -p cacheDir/$name/$version
     let destdir = get_cache_dir(backend, name, version, env);
diff --git a/src/export.rs b/src/export.rs
index 2c24d6ff..5762ab6c 100644
--- a/src/export.rs
+++ b/src/export.rs
@@ -9,14 +9,14 @@ pub fn export<T: CachedBackend + ?Sized>(
     backend: &T,
     comp: &str,
     output: Option<&str>,
-    env: Option<&str>,
+    env: &str,
 ) -> LalResult<()> {
     if comp.to_lowercase() != comp {
         return Err(CliError::InvalidComponentName(comp.into()));
     }
 
     let dir = output.unwrap_or(".");
-    info!("Export {} {} to {}", env.unwrap_or("global"), comp, dir);
+    info!("Export {} {} to {}", env, comp, dir);
 
     let mut component_name = comp; // this is only correct if no =version suffix
     let tarname = if comp.contains('=') {
diff --git a/src/storage/download.rs b/src/storage/download.rs
index f798b05f..257feaa0 100644
--- a/src/storage/download.rs
+++ b/src/storage/download.rs
@@ -8,7 +8,7 @@ fn is_cached<T: Backend + ?Sized>(
     backend: &T,
     name: &str,
     version: u32,
-    env: Option<&str>,
+    env: &str,
 ) -> bool {
     get_cache_dir(backend, name, version, env).is_dir()
 }
@@ -17,14 +17,13 @@ fn get_cache_dir<T: Backend + ?Sized>(
     backend: &T,
     name: &str,
     version: u32,
-    env: Option<&str>,
+    env: &str,
 ) -> PathBuf {
     let cache = backend.get_cache_dir();
-    let pth = Path::new(&cache);
-    match env {
-    }.join(name)
+    Path::new(&cache)
+        .join("environments")
+        .join(env)
+        .join(name)
         .join(version.to_string())
 }
 
@@ -32,7 +31,7 @@ fn store_tarball<T: Backend + ?Sized>(
     backend: &T,
     name: &str,
     version: u32,
-    env: Option<&str>,
+    env: &str,
 ) -> Result<(), CliError> {
     // 1. mkdir -p cacheDir/$name/$version
     let destdir = get_cache_dir(backend, name, version, env);
@@ -99,7 +98,7 @@ where
         &self,
         name: &str,
         version: Option<u32>,
-        env: Option<&str>,
+        env: &str,
     ) -> LalResult<(PathBuf, Component)> {
         trace!("Locate component {}", name);
 
@@ -125,7 +124,7 @@ where
         &self,
         name: &str,
         version: Option<u32>,
-        env: Option<&str>,
+        env: &str,
     ) -> LalResult<Component> {
         let (tarname, component) = self.retrieve_published_component(name, version, env)?;
 
diff --git a/src/storage/traits.rs b/src/storage/traits.rs
index d872b2a6..5ddfa601 100644
--- a/src/storage/traits.rs
+++ b/src/storage/traits.rs
@@ -78,7 +78,7 @@ pub trait CachedBackend {
         &self,
         name: &str,
         version: Option<u32>,
-        env: Option<&str>,
+        env: &str,
     ) -> LalResult<(PathBuf, Component)>;
 
     /// Retrieve the location to a stashed component
@@ -89,7 +89,7 @@ pub trait CachedBackend {
         &self,
         name: &str,
         version: Option<u32>,
-        env: Option<&str>,
+        env: &str,
     ) -> LalResult<Component>;
 
     /// Retrieve and unpack a stashed component to INPUT
```

**Comment by clux** [comment]
If we do this, we should probably do it alongside https://github.com/lalbuild/lal/pull/4 to ensure we got it good enough to be able to have a local storage implementation in a sane way. Also we've started renaming trait methods in there already in the middle of history, so whatever.

**Comment by bencord0** [comment]
We can reorder history and split out the trait renames into another PR.
Since traits are internal to the final binary, that doesn't require a version bump.

**Comment by clux** [comment]
Ok, I'll cherry-pick out the renames from this PR.

**Comment by clux** [comment]
Done in #8 
Some breaking changes. Next version will have to be 4.0.0
